
# General arguments
cpu: False
modelPath: "pretrained/dns64-a7761ff99a7d5bb6.th"
savePath: "exp/Demucs"
seed: 2


# Model related
model: Demucs
demucs:
    chin: 1
    chout: 1
    hidden: 64
    max_hidden: 10000
    causal: true
    glu: true
    depth: 5
    kernel_size: 8
    stride: 4
    normalize: true
    resample: 4
    growth: 2
    rescale: 0.1


# Data related
dataPath: "/data-ssd/Datasets/DNS-Challenge/datasets"
fs: 16000
segment: 4
stride: 1    # in seconds, how much to stride between training examples
pad: true   # if training sample is too short, pad it
matching: dns


# Training related
batch_size: 64
epochs: 50
num_workers: 4
optim: Adam
lr: 3.0e-4
beta2: 0.999
